name: "HA Cover AI"
description: "CoverAI addon for homeassistant"
version: "1.0.0"
slug: "cover_ai"
homeassistant_api: true

options:
  custom_trigger_event: "run_model_eval"
  position_trigger_delta: 20
  tilt_trigger_delta: 10

schema:
  custom_trigger_event: str
  position_trigger_delta: int
  tilt_trigger_delta: int

init: false
arch:
  - aarch64
  - amd64